### ISSUE TITLE
这里为什么斜杠不一样

### ISSUE THREAD

**Issue by duoshoumiao** [aJacke/bgame_wiki_pcr#1]
![30440c6e6b6a08024b695f69f011049c](https://github.com/user-attachments/assets/1545c6bd-4b9c-4b62-8501-8ec6a5703ca3)

**Comment by aJacke** [comment]
这哪段代码的

**Comment by aJacke** [comment]
> 这哪段代码的
是没法使用吗

**Comment by aJacke** [comment]
是没法使用吗> 这哪段代码的

**Comment by duoshoumiao** [comment]
> 这哪段代码的

搞定了，我以为r是resource。

**Comment by aJacke** [comment]
> 这哪段代码的

是没法正常使用吗

**Comment by duoshoumiao** [comment]
> > 这哪段代码的
> 
> 是没法正常使用吗
> 
能正常使用了  刚解决
